// ... mevcut kod ...
// NOT: Bu dosyadaki dosya yazma işlemleri sadece local geliştirme için kullanılmalıdır. Vercel'de çalışmaz!
// Vercel'de QR kodu sadece toDataURL ile response olarak üretin.
// ... mevcut kod ... 